// Generated by generate_from_gir.py
// DO NOT EDIT THIS FILE DIRECTLY

const addon = require('./build/Release/flatpak.node');

class BundleRef {
  constructor(handle) {
    this._handle = handle;
  }

  getAppstream() {
    const result = addon.BundleRef.getAppstream(this._handle);
    return result;
  }

  getFile() {
    const result = addon.BundleRef.getFile(this._handle);
    return result;
  }

  getIcon(size) {
    const result = addon.BundleRef.getIcon(this._handle, size);
    return result;
  }

  getInstalledSize() {
    const result = addon.BundleRef.getInstalledSize(this._handle);
    return result;
  }

  getMetadata() {
    const result = addon.BundleRef.getMetadata(this._handle);
    return result;
  }

  getOrigin() {
    const result = addon.BundleRef.getOrigin(this._handle);
    return result;
  }

  getRuntimeRepoUrl() {
    const result = addon.BundleRef.getRuntimeRepoUrl(this._handle);
    return result;
  }

  formatRef() {
    const result = addon.Ref.formatRef(this._handle);
    return result;
  }

  formatRefCached() {
    const result = addon.Ref.formatRefCached(this._handle);
    return result;
  }

  getArch() {
    const result = addon.Ref.getArch(this._handle);
    return result;
  }

  getBranch() {
    const result = addon.Ref.getBranch(this._handle);
    return result;
  }

  getCollectionId() {
    const result = addon.Ref.getCollectionId(this._handle);
    return result;
  }

  getCommit() {
    const result = addon.Ref.getCommit(this._handle);
    return result;
  }

  getKind() {
    const result = addon.Ref.getKind(this._handle);
    return result;
  }

  getName() {
    const result = addon.Ref.getName(this._handle);
    return result;
  }

  get file() {
    return this.get_file();
  }

  set file(value) {
    this.set_file(value);
  }

  get arch() {
    return this.get_arch();
  }

  set arch(value) {
    this.set_arch(value);
  }

  get branch() {
    return this.get_branch();
  }

  set branch(value) {
    this.set_branch(value);
  }

  get collectionId() {
    return this.get_collection_id();
  }

  set collectionId(value) {
    this.set_collection_id(value);
  }

  get commit() {
    return this.get_commit();
  }

  set commit(value) {
    this.set_commit(value);
  }

  get kind() {
    return this.get_kind();
  }

  set kind(value) {
    this.set_kind(value);
  }

  get name() {
    return this.get_name();
  }

  set name(value) {
    this.set_name(value);
  }


  get _native() {
    return this._handle;
  }

  free() {
    // Drop our reference to the native handle so the underlying
    // GObject can be unref'd by the external finalizer. After this
    // the wrapper must not be used again.
    this._handle = null;
  }

  // Explicit resource management: enables `using x = ...` syntax.
  [Symbol.dispose]() {
    this.free();
  }
}

BundleRef.create = function(file) {
  const handle = addon.BundleRef.new(file);
  return new BundleRef(handle);
};


class Installation {
  constructor(handle) {
    this._handle = handle;
  }

  addRemote(remote, if_needed, cancellable) {
    const result = addon.Installation.addRemote(this._handle, remote, if_needed, cancellable);
    return result;
  }

  cleanupLocalRefsSync(cancellable) {
    const result = addon.Installation.cleanupLocalRefsSync(this._handle, cancellable);
    return result;
  }

  createMonitor(cancellable) {
    const result = addon.Installation.createMonitor(this._handle, cancellable);
    return result;
  }

  dropCaches(cancellable) {
    const result = addon.Installation.dropCaches(this._handle, cancellable);
    return result;
  }

  fetchRemoteMetadataSync(remote_name, ref, cancellable) {
    const result = addon.Installation.fetchRemoteMetadataSync(this._handle, remote_name, ref, cancellable);
    return result;
  }

  fetchRemoteRefSync(remote_name, kind, name, arch, branch, cancellable) {
    const result = addon.Installation.fetchRemoteRefSync(this._handle, remote_name, kind, name, arch, branch, cancellable);
    return result;
  }

  fetchRemoteRefSyncFull(remote_name, kind, name, arch, branch, flags, cancellable) {
    const result = addon.Installation.fetchRemoteRefSyncFull(this._handle, remote_name, kind, name, arch, branch, flags, cancellable);
    return result;
  }

  fetchRemoteSizeSync(remote_name, ref, download_size, installed_size, cancellable) {
    const result = addon.Installation.fetchRemoteSizeSync(this._handle, remote_name, ref, download_size, installed_size, cancellable);
    return result;
  }

  getConfig(key, cancellable) {
    const result = addon.Installation.getConfig(this._handle, key, cancellable);
    return result;
  }

  getCurrentInstalledApp(name, cancellable) {
    const result = addon.Installation.getCurrentInstalledApp(this._handle, name, cancellable);
    return result;
  }

  getDefaultLanguages() {
    const result = addon.Installation.getDefaultLanguages(this._handle);
    return result;
  }

  getDefaultLocales() {
    const result = addon.Installation.getDefaultLocales(this._handle);
    return result;
  }

  getDisplayName() {
    const result = addon.Installation.getDisplayName(this._handle);
    return result;
  }

  getId() {
    const result = addon.Installation.getId(this._handle);
    return result;
  }

  getInstalledRef(kind, name, arch, branch, cancellable) {
    const result = addon.Installation.getInstalledRef(this._handle, kind, name, arch, branch, cancellable);
    return result;
  }

  getIsUser() {
    const result = addon.Installation.getIsUser(this._handle);
    return result;
  }

  getMinFreeSpaceBytes(out_bytes) {
    const result = addon.Installation.getMinFreeSpaceBytes(this._handle, out_bytes);
    return result;
  }

  getNoInteraction() {
    const result = addon.Installation.getNoInteraction(this._handle);
    return result;
  }

  getPath() {
    const result = addon.Installation.getPath(this._handle);
    return result;
  }

  getPriority() {
    const result = addon.Installation.getPriority(this._handle);
    return result;
  }

  getRemoteByName(name, cancellable) {
    const result = addon.Installation.getRemoteByName(this._handle, name, cancellable);
    return result;
  }

  getStorageType() {
    const result = addon.Installation.getStorageType(this._handle);
    return result;
  }

  installRefFile(ref_file_data, cancellable) {
    const result = addon.Installation.installRefFile(this._handle, ref_file_data, cancellable);
    return result;
  }

  launch(name, arch, branch, commit, cancellable) {
    const result = addon.Installation.launch(this._handle, name, arch, branch, commit, cancellable);
    return result;
  }

  launchFull(flags, name, arch, branch, commit, instance_out, cancellable) {
    const result = addon.Installation.launchFull(this._handle, flags, name, arch, branch, commit, instance_out, cancellable);
    return result;
  }

  listInstalledRefs(cancellable) {
    const result = addon.Installation.listInstalledRefs(this._handle, cancellable);
    if (Array.isArray(result)) {
      return result.map(item => {
        if (!item) return item;
        // Check if already wrapped
        if (item._native !== undefined) return item;
        // Wrap in appropriate class
        const wrapperClass = InstalledRef;
        return wrapperClass ? new wrapperClass(item) : item;
      });
    }
    return result;
  }

  listInstalledRefsByKind(kind, cancellable) {
    const result = addon.Installation.listInstalledRefsByKind(this._handle, kind, cancellable);
    if (Array.isArray(result)) {
      return result.map(item => {
        if (!item) return item;
        // Check if already wrapped
        if (item._native !== undefined) return item;
        // Wrap in appropriate class
        const wrapperClass = InstalledRef;
        return wrapperClass ? new wrapperClass(item) : item;
      });
    }
    return result;
  }

  listInstalledRefsForUpdate(cancellable) {
    const result = addon.Installation.listInstalledRefsForUpdate(this._handle, cancellable);
    if (Array.isArray(result)) {
      return result.map(item => {
        if (!item) return item;
        // Check if already wrapped
        if (item._native !== undefined) return item;
        // Wrap in appropriate class
        const wrapperClass = InstalledRef;
        return wrapperClass ? new wrapperClass(item) : item;
      });
    }
    return result;
  }

  listInstalledRelatedRefsSync(remote_name, ref, cancellable) {
    const result = addon.Installation.listInstalledRelatedRefsSync(this._handle, remote_name, ref, cancellable);
    if (Array.isArray(result)) {
      return result.map(item => {
        if (!item) return item;
        // Check if already wrapped
        if (item._native !== undefined) return item;
        // Wrap in appropriate class
        const wrapperClass = RelatedRef;
        return wrapperClass ? new wrapperClass(item) : item;
      });
    }
    return result;
  }

  listPinnedRefs(arch, cancellable) {
    const result = addon.Installation.listPinnedRefs(this._handle, arch, cancellable);
    if (Array.isArray(result)) {
      return result.map(item => {
        if (!item) return item;
        // Check if already wrapped
        if (item._native !== undefined) return item;
        // Wrap in appropriate class
        const wrapperClass = InstalledRef;
        return wrapperClass ? new wrapperClass(item) : item;
      });
    }
    return result;
  }

  listRemoteRefsSync(remote_or_uri, cancellable) {
    const result = addon.Installation.listRemoteRefsSync(this._handle, remote_or_uri, cancellable);
    if (Array.isArray(result)) {
      return result.map(item => {
        if (!item) return item;
        // Check if already wrapped
        if (item._native !== undefined) return item;
        // Wrap in appropriate class
        const wrapperClass = RemoteRef;
        return wrapperClass ? new wrapperClass(item) : item;
      });
    }
    return result;
  }

  listRemoteRefsSyncFull(remote_or_uri, flags, cancellable) {
    const result = addon.Installation.listRemoteRefsSyncFull(this._handle, remote_or_uri, flags, cancellable);
    if (Array.isArray(result)) {
      return result.map(item => {
        if (!item) return item;
        // Check if already wrapped
        if (item._native !== undefined) return item;
        // Wrap in appropriate class
        const wrapperClass = RemoteRef;
        return wrapperClass ? new wrapperClass(item) : item;
      });
    }
    return result;
  }

  listRemoteRelatedRefsForInstalledSync(remote_name, ref, cancellable) {
    const result = addon.Installation.listRemoteRelatedRefsForInstalledSync(this._handle, remote_name, ref, cancellable);
    if (Array.isArray(result)) {
      return result.map(item => {
        if (!item) return item;
        // Check if already wrapped
        if (item._native !== undefined) return item;
        // Wrap in appropriate class
        const wrapperClass = RelatedRef;
        return wrapperClass ? new wrapperClass(item) : item;
      });
    }
    return result;
  }

  listRemoteRelatedRefsSync(remote_name, ref, cancellable) {
    const result = addon.Installation.listRemoteRelatedRefsSync(this._handle, remote_name, ref, cancellable);
    if (Array.isArray(result)) {
      return result.map(item => {
        if (!item) return item;
        // Check if already wrapped
        if (item._native !== undefined) return item;
        // Wrap in appropriate class
        const wrapperClass = RelatedRef;
        return wrapperClass ? new wrapperClass(item) : item;
      });
    }
    return result;
  }

  listRemotes(cancellable) {
    const result = addon.Installation.listRemotes(this._handle, cancellable);
    if (Array.isArray(result)) {
      return result.map(item => {
        if (!item) return item;
        // Check if already wrapped
        if (item._native !== undefined) return item;
        // Wrap in appropriate class
        const wrapperClass = Remote;
        return wrapperClass ? new wrapperClass(item) : item;
      });
    }
    return result;
  }

  listUnusedRefs(arch, cancellable) {
    const result = addon.Installation.listUnusedRefs(this._handle, arch, cancellable);
    if (Array.isArray(result)) {
      return result.map(item => {
        if (!item) return item;
        // Check if already wrapped
        if (item._native !== undefined) return item;
        // Wrap in appropriate class
        const wrapperClass = InstalledRef;
        return wrapperClass ? new wrapperClass(item) : item;
      });
    }
    return result;
  }

  listUnusedRefsWithOptions(arch, metadata_injection, options, cancellable) {
    const result = addon.Installation.listUnusedRefsWithOptions(this._handle, arch, metadata_injection, options, cancellable);
    if (Array.isArray(result)) {
      return result.map(item => {
        if (!item) return item;
        // Check if already wrapped
        if (item._native !== undefined) return item;
        // Wrap in appropriate class
        const wrapperClass = InstalledRef;
        return wrapperClass ? new wrapperClass(item) : item;
      });
    }
    return result;
  }

  loadAppOverrides(app_id, cancellable) {
    const result = addon.Installation.loadAppOverrides(this._handle, app_id, cancellable);
    return result;
  }

  modifyRemote(remote, cancellable) {
    const result = addon.Installation.modifyRemote(this._handle, remote, cancellable);
    return result;
  }

  pruneLocalRepo(cancellable) {
    const result = addon.Installation.pruneLocalRepo(this._handle, cancellable);
    return result;
  }

  removeLocalRefSync(remote_name, ref, cancellable) {
    const result = addon.Installation.removeLocalRefSync(this._handle, remote_name, ref, cancellable);
    return result;
  }

  removeRemote(name, cancellable) {
    const result = addon.Installation.removeRemote(this._handle, name, cancellable);
    return result;
  }

  runTriggers(cancellable) {
    const result = addon.Installation.runTriggers(this._handle, cancellable);
    return result;
  }

  setConfigSync(key, value, cancellable) {
    const result = addon.Installation.setConfigSync(this._handle, key, value, cancellable);
    return result;
  }

  setNoInteraction(no_interaction) {
    const result = addon.Installation.setNoInteraction(this._handle, no_interaction);
    return result;
  }

  updateAppstreamSync(remote_name, arch, out_changed, cancellable) {
    const result = addon.Installation.updateAppstreamSync(this._handle, remote_name, arch, out_changed, cancellable);
    return result;
  }

  updateRemoteSync(name, cancellable) {
    const result = addon.Installation.updateRemoteSync(this._handle, name, cancellable);
    return result;
  }


  get _native() {
    return this._handle;
  }

  free() {
    // Drop our reference to the native handle so the underlying
    // GObject can be unref'd by the external finalizer. After this
    // the wrapper must not be used again.
    this._handle = null;
  }

  // Explicit resource management: enables `using x = ...` syntax.
  [Symbol.dispose]() {
    this.free();
  }
}

Installation.create = function(path, user, cancellable) {
  const handle = addon.Installation.new(path, user, cancellable);
  return new Installation(handle);
};


class InstalledRef {
  constructor(handle) {
    this._handle = handle;
  }

  getAppdataContentRating() {
    const result = addon.InstalledRef.getAppdataContentRating(this._handle);
    return result;
  }

  getAppdataContentRatingType() {
    const result = addon.InstalledRef.getAppdataContentRatingType(this._handle);
    return result;
  }

  getAppdataLicense() {
    const result = addon.InstalledRef.getAppdataLicense(this._handle);
    return result;
  }

  getAppdataName() {
    const result = addon.InstalledRef.getAppdataName(this._handle);
    return result;
  }

  getAppdataSummary() {
    const result = addon.InstalledRef.getAppdataSummary(this._handle);
    return result;
  }

  getAppdataVersion() {
    const result = addon.InstalledRef.getAppdataVersion(this._handle);
    return result;
  }

  getDeployDir() {
    const result = addon.InstalledRef.getDeployDir(this._handle);
    return result;
  }

  getEol() {
    const result = addon.InstalledRef.getEol(this._handle);
    return result;
  }

  getEolRebase() {
    const result = addon.InstalledRef.getEolRebase(this._handle);
    return result;
  }

  getInstalledSize() {
    const result = addon.InstalledRef.getInstalledSize(this._handle);
    return result;
  }

  getIsCurrent() {
    const result = addon.InstalledRef.getIsCurrent(this._handle);
    return result;
  }

  getLatestCommit() {
    const result = addon.InstalledRef.getLatestCommit(this._handle);
    return result;
  }

  getOrigin() {
    const result = addon.InstalledRef.getOrigin(this._handle);
    return result;
  }

  getSubpaths() {
    const result = addon.InstalledRef.getSubpaths(this._handle);
    return result;
  }

  loadAppdata(cancellable) {
    const result = addon.InstalledRef.loadAppdata(this._handle, cancellable);
    return result;
  }

  loadMetadata(cancellable) {
    const result = addon.InstalledRef.loadMetadata(this._handle, cancellable);
    return result;
  }

  formatRef() {
    const result = addon.Ref.formatRef(this._handle);
    return result;
  }

  formatRefCached() {
    const result = addon.Ref.formatRefCached(this._handle);
    return result;
  }

  getArch() {
    const result = addon.Ref.getArch(this._handle);
    return result;
  }

  getBranch() {
    const result = addon.Ref.getBranch(this._handle);
    return result;
  }

  getCollectionId() {
    const result = addon.Ref.getCollectionId(this._handle);
    return result;
  }

  getCommit() {
    const result = addon.Ref.getCommit(this._handle);
    return result;
  }

  getKind() {
    const result = addon.Ref.getKind(this._handle);
    return result;
  }

  getName() {
    const result = addon.Ref.getName(this._handle);
    return result;
  }

  get appdataContentRating() {
    return this.get_appdata_content_rating();
  }

  set appdataContentRating(value) {
    this.set_appdata_content_rating(value);
  }

  get appdataContentRatingType() {
    return this.get_appdata_content_rating_type();
  }

  set appdataContentRatingType(value) {
    this.set_appdata_content_rating_type(value);
  }

  get appdataLicense() {
    return this.get_appdata_license();
  }

  set appdataLicense(value) {
    this.set_appdata_license(value);
  }

  get appdataName() {
    return this.get_appdata_name();
  }

  set appdataName(value) {
    this.set_appdata_name(value);
  }

  get appdataSummary() {
    return this.get_appdata_summary();
  }

  set appdataSummary(value) {
    this.set_appdata_summary(value);
  }

  get appdataVersion() {
    return this.get_appdata_version();
  }

  set appdataVersion(value) {
    this.set_appdata_version(value);
  }

  get deployDir() {
    return this.get_deploy_dir();
  }

  set deployDir(value) {
    this.set_deploy_dir(value);
  }

  get endOfLife() {
    return this.get_end_of_life();
  }

  set endOfLife(value) {
    this.set_end_of_life(value);
  }

  get endOfLifeRebase() {
    return this.get_end_of_life_rebase();
  }

  set endOfLifeRebase(value) {
    this.set_end_of_life_rebase(value);
  }

  get installedSize() {
    return this.get_installed_size();
  }

  set installedSize(value) {
    this.set_installed_size(value);
  }

  get isCurrent() {
    return this.get_is_current();
  }

  set isCurrent(value) {
    this.set_is_current(value);
  }

  get latestCommit() {
    return this.get_latest_commit();
  }

  set latestCommit(value) {
    this.set_latest_commit(value);
  }

  get origin() {
    return this.get_origin();
  }

  set origin(value) {
    this.set_origin(value);
  }

  get arch() {
    return this.get_arch();
  }

  set arch(value) {
    this.set_arch(value);
  }

  get branch() {
    return this.get_branch();
  }

  set branch(value) {
    this.set_branch(value);
  }

  get collectionId() {
    return this.get_collection_id();
  }

  set collectionId(value) {
    this.set_collection_id(value);
  }

  get commit() {
    return this.get_commit();
  }

  set commit(value) {
    this.set_commit(value);
  }

  get kind() {
    return this.get_kind();
  }

  set kind(value) {
    this.set_kind(value);
  }

  get name() {
    return this.get_name();
  }

  set name(value) {
    this.set_name(value);
  }


  get _native() {
    return this._handle;
  }

  free() {
    // Drop our reference to the native handle so the underlying
    // GObject can be unref'd by the external finalizer. After this
    // the wrapper must not be used again.
    this._handle = null;
  }

  // Explicit resource management: enables `using x = ...` syntax.
  [Symbol.dispose]() {
    this.free();
  }
}


class Instance {
  constructor(handle) {
    this._handle = handle;
  }

  getApp() {
    const result = addon.Instance.getApp(this._handle);
    return result;
  }

  getArch() {
    const result = addon.Instance.getArch(this._handle);
    return result;
  }

  getBranch() {
    const result = addon.Instance.getBranch(this._handle);
    return result;
  }

  getChildPid() {
    const result = addon.Instance.getChildPid(this._handle);
    return result;
  }

  getCommit() {
    const result = addon.Instance.getCommit(this._handle);
    return result;
  }

  getId() {
    const result = addon.Instance.getId(this._handle);
    return result;
  }

  getInfo() {
    const result = addon.Instance.getInfo(this._handle);
    return result;
  }

  getPid() {
    const result = addon.Instance.getPid(this._handle);
    return result;
  }

  getRuntime() {
    const result = addon.Instance.getRuntime(this._handle);
    return result;
  }

  getRuntimeCommit() {
    const result = addon.Instance.getRuntimeCommit(this._handle);
    return result;
  }

  isRunning() {
    const result = addon.Instance.isRunning(this._handle);
    return result;
  }


  get _native() {
    return this._handle;
  }

  free() {
    // Drop our reference to the native handle so the underlying
    // GObject can be unref'd by the external finalizer. After this
    // the wrapper must not be used again.
    this._handle = null;
  }

  // Explicit resource management: enables `using x = ...` syntax.
  [Symbol.dispose]() {
    this.free();
  }
}


class Ref {
  constructor(handle) {
    this._handle = handle;
  }

  formatRef() {
    const result = addon.Ref.formatRef(this._handle);
    return result;
  }

  formatRefCached() {
    const result = addon.Ref.formatRefCached(this._handle);
    return result;
  }

  getArch() {
    const result = addon.Ref.getArch(this._handle);
    return result;
  }

  getBranch() {
    const result = addon.Ref.getBranch(this._handle);
    return result;
  }

  getCollectionId() {
    const result = addon.Ref.getCollectionId(this._handle);
    return result;
  }

  getCommit() {
    const result = addon.Ref.getCommit(this._handle);
    return result;
  }

  getKind() {
    const result = addon.Ref.getKind(this._handle);
    return result;
  }

  getName() {
    const result = addon.Ref.getName(this._handle);
    return result;
  }

  get arch() {
    return this.get_arch();
  }

  set arch(value) {
    this.set_arch(value);
  }

  get branch() {
    return this.get_branch();
  }

  set branch(value) {
    this.set_branch(value);
  }

  get collectionId() {
    return this.get_collection_id();
  }

  set collectionId(value) {
    this.set_collection_id(value);
  }

  get commit() {
    return this.get_commit();
  }

  set commit(value) {
    this.set_commit(value);
  }

  get kind() {
    return this.get_kind();
  }

  set kind(value) {
    this.set_kind(value);
  }

  get name() {
    return this.get_name();
  }

  set name(value) {
    this.set_name(value);
  }


  get _native() {
    return this._handle;
  }

  free() {
    // Drop our reference to the native handle so the underlying
    // GObject can be unref'd by the external finalizer. After this
    // the wrapper must not be used again.
    this._handle = null;
  }

  // Explicit resource management: enables `using x = ...` syntax.
  [Symbol.dispose]() {
    this.free();
  }
}


class RelatedRef {
  constructor(handle) {
    this._handle = handle;
  }

  getSubpaths() {
    const result = addon.RelatedRef.getSubpaths(this._handle);
    return result;
  }

  shouldAutoprune() {
    const result = addon.RelatedRef.shouldAutoprune(this._handle);
    return result;
  }

  shouldDelete() {
    const result = addon.RelatedRef.shouldDelete(this._handle);
    return result;
  }

  shouldDownload() {
    const result = addon.RelatedRef.shouldDownload(this._handle);
    return result;
  }

  formatRef() {
    const result = addon.Ref.formatRef(this._handle);
    return result;
  }

  formatRefCached() {
    const result = addon.Ref.formatRefCached(this._handle);
    return result;
  }

  getArch() {
    const result = addon.Ref.getArch(this._handle);
    return result;
  }

  getBranch() {
    const result = addon.Ref.getBranch(this._handle);
    return result;
  }

  getCollectionId() {
    const result = addon.Ref.getCollectionId(this._handle);
    return result;
  }

  getCommit() {
    const result = addon.Ref.getCommit(this._handle);
    return result;
  }

  getKind() {
    const result = addon.Ref.getKind(this._handle);
    return result;
  }

  getName() {
    const result = addon.Ref.getName(this._handle);
    return result;
  }

  get shouldAutoprune() {
    return this.get_should_autoprune();
  }

  set shouldAutoprune(value) {
    this.set_should_autoprune(value);
  }

  get shouldDelete() {
    return this.get_should_delete();
  }

  set shouldDelete(value) {
    this.set_should_delete(value);
  }

  get shouldDownload() {
    return this.get_should_download();
  }

  set shouldDownload(value) {
    this.set_should_download(value);
  }

  get arch() {
    return this.get_arch();
  }

  set arch(value) {
    this.set_arch(value);
  }

  get branch() {
    return this.get_branch();
  }

  set branch(value) {
    this.set_branch(value);
  }

  get collectionId() {
    return this.get_collection_id();
  }

  set collectionId(value) {
    this.set_collection_id(value);
  }

  get commit() {
    return this.get_commit();
  }

  set commit(value) {
    this.set_commit(value);
  }

  get kind() {
    return this.get_kind();
  }

  set kind(value) {
    this.set_kind(value);
  }

  get name() {
    return this.get_name();
  }

  set name(value) {
    this.set_name(value);
  }


  get _native() {
    return this._handle;
  }

  free() {
    // Drop our reference to the native handle so the underlying
    // GObject can be unref'd by the external finalizer. After this
    // the wrapper must not be used again.
    this._handle = null;
  }

  // Explicit resource management: enables `using x = ...` syntax.
  [Symbol.dispose]() {
    this.free();
  }
}


class Remote {
  constructor(handle) {
    this._handle = handle;
  }

  getAppstreamDir(arch) {
    const result = addon.Remote.getAppstreamDir(this._handle, arch);
    return result;
  }

  getAppstreamTimestamp(arch) {
    const result = addon.Remote.getAppstreamTimestamp(this._handle, arch);
    return result;
  }

  getCollectionId() {
    const result = addon.Remote.getCollectionId(this._handle);
    return result;
  }

  getComment() {
    const result = addon.Remote.getComment(this._handle);
    return result;
  }

  getDefaultBranch() {
    const result = addon.Remote.getDefaultBranch(this._handle);
    return result;
  }

  getDescription() {
    const result = addon.Remote.getDescription(this._handle);
    return result;
  }

  getDisabled() {
    const result = addon.Remote.getDisabled(this._handle);
    return result;
  }

  getFilter() {
    const result = addon.Remote.getFilter(this._handle);
    return result;
  }

  getGpgVerify() {
    const result = addon.Remote.getGpgVerify(this._handle);
    return result;
  }

  getHomepage() {
    const result = addon.Remote.getHomepage(this._handle);
    return result;
  }

  getIcon() {
    const result = addon.Remote.getIcon(this._handle);
    return result;
  }

  getMainRef() {
    const result = addon.Remote.getMainRef(this._handle);
    return result;
  }

  getName() {
    const result = addon.Remote.getName(this._handle);
    return result;
  }

  getNodeps() {
    const result = addon.Remote.getNodeps(this._handle);
    return result;
  }

  getNoenumerate() {
    const result = addon.Remote.getNoenumerate(this._handle);
    return result;
  }

  getPrio() {
    const result = addon.Remote.getPrio(this._handle);
    return result;
  }

  getRemoteType() {
    const result = addon.Remote.getRemoteType(this._handle);
    return result;
  }

  getTitle() {
    const result = addon.Remote.getTitle(this._handle);
    return result;
  }

  getUrl() {
    const result = addon.Remote.getUrl(this._handle);
    return result;
  }

  setCollectionId(collection_id) {
    const result = addon.Remote.setCollectionId(this._handle, collection_id);
    return result;
  }

  setComment(comment) {
    const result = addon.Remote.setComment(this._handle, comment);
    return result;
  }

  setDefaultBranch(default_branch) {
    const result = addon.Remote.setDefaultBranch(this._handle, default_branch);
    return result;
  }

  setDescription(description) {
    const result = addon.Remote.setDescription(this._handle, description);
    return result;
  }

  setDisabled(disabled) {
    const result = addon.Remote.setDisabled(this._handle, disabled);
    return result;
  }

  setFilter(filter_path) {
    const result = addon.Remote.setFilter(this._handle, filter_path);
    return result;
  }

  setGpgKey(gpg_key) {
    const result = addon.Remote.setGpgKey(this._handle, gpg_key);
    return result;
  }

  setGpgVerify(gpg_verify) {
    const result = addon.Remote.setGpgVerify(this._handle, gpg_verify);
    return result;
  }

  setHomepage(homepage) {
    const result = addon.Remote.setHomepage(this._handle, homepage);
    return result;
  }

  setIcon(icon) {
    const result = addon.Remote.setIcon(this._handle, icon);
    return result;
  }

  setMainRef(main_ref) {
    const result = addon.Remote.setMainRef(this._handle, main_ref);
    return result;
  }

  setNodeps(nodeps) {
    const result = addon.Remote.setNodeps(this._handle, nodeps);
    return result;
  }

  setNoenumerate(noenumerate) {
    const result = addon.Remote.setNoenumerate(this._handle, noenumerate);
    return result;
  }

  setPrio(prio) {
    const result = addon.Remote.setPrio(this._handle, prio);
    return result;
  }

  setTitle(title) {
    const result = addon.Remote.setTitle(this._handle, title);
    return result;
  }

  setUrl(url) {
    const result = addon.Remote.setUrl(this._handle, url);
    return result;
  }

  get name() {
    return this.get_name();
  }

  set name(value) {
    this.set_name(value);
  }

  get type() {
    return this.get_type();
  }

  set type(value) {
    this.set_type(value);
  }


  get _native() {
    return this._handle;
  }

  free() {
    // Drop our reference to the native handle so the underlying
    // GObject can be unref'd by the external finalizer. After this
    // the wrapper must not be used again.
    this._handle = null;
  }

  // Explicit resource management: enables `using x = ...` syntax.
  [Symbol.dispose]() {
    this.free();
  }
}

Remote.create = function(name) {
  const handle = addon.Remote.new(name);
  return new Remote(handle);
};


class RemoteRef {
  constructor(handle) {
    this._handle = handle;
  }

  getDownloadSize() {
    const result = addon.RemoteRef.getDownloadSize(this._handle);
    return result;
  }

  getEol() {
    const result = addon.RemoteRef.getEol(this._handle);
    return result;
  }

  getEolRebase() {
    const result = addon.RemoteRef.getEolRebase(this._handle);
    return result;
  }

  getInstalledSize() {
    const result = addon.RemoteRef.getInstalledSize(this._handle);
    return result;
  }

  getMetadata() {
    const result = addon.RemoteRef.getMetadata(this._handle);
    return result;
  }

  getRemoteName() {
    const result = addon.RemoteRef.getRemoteName(this._handle);
    return result;
  }

  formatRef() {
    const result = addon.Ref.formatRef(this._handle);
    return result;
  }

  formatRefCached() {
    const result = addon.Ref.formatRefCached(this._handle);
    return result;
  }

  getArch() {
    const result = addon.Ref.getArch(this._handle);
    return result;
  }

  getBranch() {
    const result = addon.Ref.getBranch(this._handle);
    return result;
  }

  getCollectionId() {
    const result = addon.Ref.getCollectionId(this._handle);
    return result;
  }

  getCommit() {
    const result = addon.Ref.getCommit(this._handle);
    return result;
  }

  getKind() {
    const result = addon.Ref.getKind(this._handle);
    return result;
  }

  getName() {
    const result = addon.Ref.getName(this._handle);
    return result;
  }

  get downloadSize() {
    return this.get_download_size();
  }

  set downloadSize(value) {
    this.set_download_size(value);
  }

  get endOfLife() {
    return this.get_end_of_life();
  }

  set endOfLife(value) {
    this.set_end_of_life(value);
  }

  get endOfLifeRebase() {
    return this.get_end_of_life_rebase();
  }

  set endOfLifeRebase(value) {
    this.set_end_of_life_rebase(value);
  }

  get installedSize() {
    return this.get_installed_size();
  }

  set installedSize(value) {
    this.set_installed_size(value);
  }

  get metadata() {
    return this.get_metadata();
  }

  set metadata(value) {
    this.set_metadata(value);
  }

  get remoteName() {
    return this.get_remote_name();
  }

  set remoteName(value) {
    this.set_remote_name(value);
  }

  get arch() {
    return this.get_arch();
  }

  set arch(value) {
    this.set_arch(value);
  }

  get branch() {
    return this.get_branch();
  }

  set branch(value) {
    this.set_branch(value);
  }

  get collectionId() {
    return this.get_collection_id();
  }

  set collectionId(value) {
    this.set_collection_id(value);
  }

  get commit() {
    return this.get_commit();
  }

  set commit(value) {
    this.set_commit(value);
  }

  get kind() {
    return this.get_kind();
  }

  set kind(value) {
    this.set_kind(value);
  }

  get name() {
    return this.get_name();
  }

  set name(value) {
    this.set_name(value);
  }


  get _native() {
    return this._handle;
  }

  free() {
    // Drop our reference to the native handle so the underlying
    // GObject can be unref'd by the external finalizer. After this
    // the wrapper must not be used again.
    this._handle = null;
  }

  // Explicit resource management: enables `using x = ...` syntax.
  [Symbol.dispose]() {
    this.free();
  }
}


class Transaction {
  constructor(handle) {
    this._handle = handle;
  }

  abortWebflow(id) {
    const result = addon.Transaction.abortWebflow(this._handle, id);
    return result;
  }

  addDefaultDependencySources() {
    const result = addon.Transaction.addDefaultDependencySources(this._handle);
    return result;
  }

  addDependencySource(installation) {
    const result = addon.Transaction.addDependencySource(this._handle, installation);
    return result;
  }

  addInstallBundle(file, gpg_data) {
    const result = addon.Transaction.addInstallBundle(this._handle, file, gpg_data);
    return result;
  }

  addInstallFlatpakref(flatpakref_data) {
    const result = addon.Transaction.addInstallFlatpakref(this._handle, flatpakref_data);
    return result;
  }

  addSideloadRepo(path) {
    const result = addon.Transaction.addSideloadRepo(this._handle, path);
    return result;
  }

  addUninstall(ref) {
    const result = addon.Transaction.addUninstall(this._handle, ref);
    return result;
  }

  completeBasicAuth(id, user, password, options) {
    const result = addon.Transaction.completeBasicAuth(this._handle, id, user, password, options);
    return result;
  }

  getAutoInstallDebug() {
    const result = addon.Transaction.getAutoInstallDebug(this._handle);
    return result;
  }

  getAutoInstallSdk() {
    const result = addon.Transaction.getAutoInstallSdk(this._handle);
    return result;
  }

  getCurrentOperation() {
    const result = addon.Transaction.getCurrentOperation(this._handle);
    return result;
  }

  getIncludeUnusedUninstallOps() {
    const result = addon.Transaction.getIncludeUnusedUninstallOps(this._handle);
    return result;
  }

  getInstallation() {
    const result = addon.Transaction.getInstallation(this._handle);
    return result;
  }

  getNoDeploy() {
    const result = addon.Transaction.getNoDeploy(this._handle);
    return result;
  }

  getNoInteraction() {
    const result = addon.Transaction.getNoInteraction(this._handle);
    return result;
  }

  getNoPull() {
    const result = addon.Transaction.getNoPull(this._handle);
    return result;
  }

  getOperationForRef(remote, ref) {
    const result = addon.Transaction.getOperationForRef(this._handle, remote, ref);
    return result;
  }

  getOperations() {
    const result = addon.Transaction.getOperations(this._handle);
    return result;
  }

  getParentWindow() {
    const result = addon.Transaction.getParentWindow(this._handle);
    return result;
  }

  isEmpty() {
    const result = addon.Transaction.isEmpty(this._handle);
    return result;
  }

  run(cancellable) {
    const result = addon.Transaction.run(this._handle, cancellable);
    return result;
  }

  setAutoInstallDebug(auto_install_debug) {
    const result = addon.Transaction.setAutoInstallDebug(this._handle, auto_install_debug);
    return result;
  }

  setAutoInstallSdk(auto_install_sdk) {
    const result = addon.Transaction.setAutoInstallSdk(this._handle, auto_install_sdk);
    return result;
  }

  setDefaultArch(arch) {
    const result = addon.Transaction.setDefaultArch(this._handle, arch);
    return result;
  }

  setDisableAutoPin(disable_pin) {
    const result = addon.Transaction.setDisableAutoPin(this._handle, disable_pin);
    return result;
  }

  setDisableDependencies(disable_dependencies) {
    const result = addon.Transaction.setDisableDependencies(this._handle, disable_dependencies);
    return result;
  }

  setDisablePrune(disable_prune) {
    const result = addon.Transaction.setDisablePrune(this._handle, disable_prune);
    return result;
  }

  setDisableRelated(disable_related) {
    const result = addon.Transaction.setDisableRelated(this._handle, disable_related);
    return result;
  }

  setDisableStaticDeltas(disable_static_deltas) {
    const result = addon.Transaction.setDisableStaticDeltas(this._handle, disable_static_deltas);
    return result;
  }

  setForceUninstall(force_uninstall) {
    const result = addon.Transaction.setForceUninstall(this._handle, force_uninstall);
    return result;
  }

  setIncludeUnusedUninstallOps(include_unused_uninstall_ops) {
    const result = addon.Transaction.setIncludeUnusedUninstallOps(this._handle, include_unused_uninstall_ops);
    return result;
  }

  setNoDeploy(no_deploy) {
    const result = addon.Transaction.setNoDeploy(this._handle, no_deploy);
    return result;
  }

  setNoInteraction(no_interaction) {
    const result = addon.Transaction.setNoInteraction(this._handle, no_interaction);
    return result;
  }

  setNoPull(no_pull) {
    const result = addon.Transaction.setNoPull(this._handle, no_pull);
    return result;
  }

  setParentWindow(parent_window) {
    const result = addon.Transaction.setParentWindow(this._handle, parent_window);
    return result;
  }

  setReinstall(reinstall) {
    const result = addon.Transaction.setReinstall(this._handle, reinstall);
    return result;
  }

  get installation() {
    return this.get_installation();
  }

  set installation(value) {
    this.set_installation(value);
  }

  get noInteraction() {
    return this.get_no_interaction();
  }

  set noInteraction(value) {
    this.set_no_interaction(value);
  }


  get _native() {
    return this._handle;
  }

  free() {
    // Drop our reference to the native handle so the underlying
    // GObject can be unref'd by the external finalizer. After this
    // the wrapper must not be used again.
    this._handle = null;
  }

  // Explicit resource management: enables `using x = ...` syntax.
  [Symbol.dispose]() {
    this.free();
  }
}

Transaction.create = function(installation, cancellable) {
  const handle = addon.Transaction.new(installation, cancellable);
  return new Transaction(handle);
};


class TransactionOperation {
  constructor(handle) {
    this._handle = handle;
  }

  getBundlePath() {
    const result = addon.TransactionOperation.getBundlePath(this._handle);
    return result;
  }

  getCommit() {
    const result = addon.TransactionOperation.getCommit(this._handle);
    return result;
  }

  getDownloadSize() {
    const result = addon.TransactionOperation.getDownloadSize(this._handle);
    return result;
  }

  getInstalledSize() {
    const result = addon.TransactionOperation.getInstalledSize(this._handle);
    return result;
  }

  getIsSkipped() {
    const result = addon.TransactionOperation.getIsSkipped(this._handle);
    return result;
  }

  getMetadata() {
    const result = addon.TransactionOperation.getMetadata(this._handle);
    return result;
  }

  getOldMetadata() {
    const result = addon.TransactionOperation.getOldMetadata(this._handle);
    return result;
  }

  getOperationType() {
    const result = addon.TransactionOperation.getOperationType(this._handle);
    return result;
  }

  getRef() {
    const result = addon.TransactionOperation.getRef(this._handle);
    return result;
  }

  getRelatedToOps() {
    const result = addon.TransactionOperation.getRelatedToOps(this._handle);
    if (Array.isArray(result)) {
      return result.map(item => {
        if (!item) return item;
        // Check if already wrapped
        if (item._native !== undefined) return item;
        // Wrap in appropriate class
        const wrapperClass = TransactionOperation;
        return wrapperClass ? new wrapperClass(item) : item;
      });
    }
    return result;
  }

  getRemote() {
    const result = addon.TransactionOperation.getRemote(this._handle);
    return result;
  }

  getRequiresAuthentication() {
    const result = addon.TransactionOperation.getRequiresAuthentication(this._handle);
    return result;
  }

  getSubpaths() {
    const result = addon.TransactionOperation.getSubpaths(this._handle);
    return result;
  }


  get _native() {
    return this._handle;
  }

  free() {
    // Drop our reference to the native handle so the underlying
    // GObject can be unref'd by the external finalizer. After this
    // the wrapper must not be used again.
    this._handle = null;
  }

  // Explicit resource management: enables `using x = ...` syntax.
  [Symbol.dispose]() {
    this.free();
  }
}


class TransactionProgress {
  constructor(handle) {
    this._handle = handle;
  }

  getBytesTransferred() {
    const result = addon.TransactionProgress.getBytesTransferred(this._handle);
    return result;
  }

  getIsEstimating() {
    const result = addon.TransactionProgress.getIsEstimating(this._handle);
    return result;
  }

  getProgress() {
    const result = addon.TransactionProgress.getProgress(this._handle);
    return result;
  }

  getStartTime() {
    const result = addon.TransactionProgress.getStartTime(this._handle);
    return result;
  }

  getStatus() {
    const result = addon.TransactionProgress.getStatus(this._handle);
    return result;
  }

  setUpdateFrequency(update_interval) {
    const result = addon.TransactionProgress.setUpdateFrequency(this._handle, update_interval);
    return result;
  }


  get _native() {
    return this._handle;
  }

  free() {
    // Drop our reference to the native handle so the underlying
    // GObject can be unref'd by the external finalizer. After this
    // the wrapper must not be used again.
    this._handle = null;
  }

  // Explicit resource management: enables `using x = ...` syntax.
  [Symbol.dispose]() {
    this.free();
  }
}


function errorQuark() {
  const result = addon.errorQuark();
  return result;
}


function getAll() {
  const result = addon.getAll();
    if (Array.isArray(result)) {
      return result.map(item => {
        if (!item) return item;
        // Check if already wrapped
        if (item._native !== undefined) return item;
        // Wrap in appropriate class
        const wrapperClass = Instance;
        return wrapperClass ? new wrapperClass(item) : item;
      });
    }
  return result;
}


function portalErrorQuark() {
  const result = addon.portalErrorQuark();
  return result;
}


function parse(ref) {
  const result = addon.parse(ref);
  return result;
}


function toString(kind) {
  const result = addon.toString(kind);
  return result;
}


function getDefaultArch() {
  const result = addon.getDefaultArch();
  return result;
}


function getSupportedArches() {
  const result = addon.getSupportedArches();
  return result;
}


function getSystemInstallations(cancellable) {
  const result = addon.getSystemInstallations(cancellable);
    if (Array.isArray(result)) {
      return result.map(item => {
        if (!item) return item;
        // Check if already wrapped
        if (item._native !== undefined) return item;
        // Wrap in appropriate class
        const wrapperClass = Installation;
        return wrapperClass ? new wrapperClass(item) : item;
      });
    }
  return result;
}


// Exports
module.exports = {
  BundleRef,
  Installation,
  InstalledRef,
  Instance,
  Ref,
  RelatedRef,
  Remote,
  RemoteRef,
  Transaction,
  TransactionOperation,
  TransactionProgress,
  errorQuark,
  getAll,
  portalErrorQuark,
  parse,
  toString,
  getDefaultArch,
  getSupportedArches,
  getSystemInstallations
};