// Generated by generate_from_gir.py
// DO NOT EDIT THIS FILE DIRECTLY
//
// All classes and functions are implemented natively as
// Napi::ObjectWrap classes in the addon (src/flatpak.cc). This file
// loads the compiled addon and re-exports it. ESM cannot `require`
// directly, so we build a `require` with `createRequire`.

import { createRequire } from "node:module";

const addon = createRequire(import.meta.url)("./build/Release/flatpak.node");

export const {
  // Classes
  BundleRef,
  Installation,
  InstalledRef,
  Instance,
  Ref,
  RelatedRef,
  Remote,
  RemoteRef,
  Transaction,
  TransactionOperation,
  TransactionProgress,
  // Functions
  errorQuark,
  getAll,
  portalErrorQuark,
  parse,
  toString,
  getDefaultArch,
  getSupportedArches,
  getSystemInstallations,
} = addon;

export default addon;
